kind: pipeline
name: amd

platform:
  os: windows
  arch: amd64

steps:
- name: build
  image: golang
  commands:
  - go build
  - go run

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: golang
  commands:
  - go build
  - go run
  
